name: Development Check

on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    environment:
      name: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Success
        run: echo "🚧 Development Check Successful 🚧 "
