name: Production Deployment

on:
  release:
    types: [published]

jobs:
  deploy_production:
    name: Deploy Production
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ vars.BASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma Client
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma generate

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Sync Environment Variables
        run: |
          vercel env add BASE_URL production --force --token=${{ secrets.VERCEL_TOKEN }}
          vercel env add DATABASE_URL production --force --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Deploy Project to Vercel
        run: vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Success
        run: echo "🚀 Deploy successful 🚀 "
